feat: SM-6 Button 컴포넌트 및 스토리북 구현
prgrms-web-devcourse/Team_Alchomist_ShakeNMatch_FE pull request #4
Opened 2021-11-29 17:02 UTC by 42KIM

## 📌 내용 설명 
TextButton/ImageButton에 사용될 base인 Button 컴포넌트 구현
## 👀 이미지 또는 Gif 

## 📝 요구 사항 
+ Button 컴포넌트가 받는 props
  + children:Text 컴포넌트 또는 Image 컴포넌트
  + type: button element의 type인 'button' | 'submit' | 'reset' 중 하나
  + size: 디자인이 확정되면 버튼의 크기를 지정하는 ButtonSizeType의 값중 하나를 string으로 받는다 ex) large, default, small...
  + color: 디자인이 확정되면 버튼의 배경색을 지정하는 ButtonColorType의 값중 하나를 string으로 받는다 ex) dark, default, light...
## 💡 포인트 
단독으로 쓰이지 않고 반드시 TextButton 또는 ImageButton으로 사용되기 때문에 Button 컴포넌트 자체는 styled component로 간단하게 구현됨
## 🚩 이슈 
+ 디자인 시스템이 구축되면, 버튼의 size와 color를 결정할 type과 constants가 재정의되어야 한다.
## 🛠 피드백 반영 사항

2021-11-29 17:21 UTC, 42KIM commented
app.tsx에서 div 안에 내용 삭제 하기

2021-11-29 17:22 UTC, 42KIM commented
prop default value 설정하기

2021-11-29 18:36 UTC, 42KIM commented
JSX.Element로 수정

2021-11-29 19:52 UTC, AlangGY requested changes
Button 컴포넌트 작성하시느라 고생많으셨습니다!
이따가도 화이팅입니다 ㅎ
코드리뷰 코멘트로 남겨두었습니다.

2021-11-29 19:52 UTC, AlangGY commented on src/components/base/Button/index.tsx
> +  color: ButtonColorType;
```suggestion
  size?: ButtonSizeType;
  color?: ButtonColorType;
```
size 와 color에 대해서는 optional로 부여가 되어야하는거 아닌가요? default size와 color가 있어서, prop을 전달 받지 못했을때 default 값으로 render되는 형태가 좋을것 같은데 어떠신가요

2021-11-29 19:52 UTC, AlangGY commented on src/stories/Button.stories.tsx
> +}
Button 컴포넌트에서 작성된 ButtonProps 인터페이스를 import하여 사용하는것은 어떨까요?

2021-11-30 06:22 UTC, 42KIM commented on src/components/base/Button/index.tsx
> +  color: ButtonColorType;
default를 처음에 생각 안 했다가 뒤늦게 디폴트를 주는 걸 생각했는데
디폴트를 줄 거면 말씀하신대로 옵셔널로 주는 게 맞을 것 같아요

2021-11-30 06:23 UTC, 42KIM commented on src/stories/Button.stories.tsx
> +}
@AlangGY 해당 컴포넌트 prop은 거기서 정의하기로 했으니까 export 하고 싶지 않았는데
스토리북 대문에 결국,,
이럴꺼면 그냥 prop interface에 대해서도 전부 모듈화해서 관리해야하나

2021-11-30 19:42 UTC, AlangGY commented on src/stories/Button.stories.tsx
> +}
@42KIM 
저도 그부분에 동감합니다. 다만 다시 한번 생각해보았는데,
코드의 길이를 더 짧게한다라는것에만 초점을 둔다면, export 6글자 및 import 구문 코드 추가로 같은 기능을 구현하는 거라면, export 해서 쓰는것이 더 이득이라고 볼수있지 않을까요?

2021-12-01 06:10 UTC, sshyukk reviewed
안녕하세요 사휘님~ 코드 보면서 궁금한 부분 몇 개 적어봤습니다 ㅎㅎ
덕분에 읽어 보면서 많은 도움이 되었네요!!

2021-12-01 06:10 UTC, sshyukk commented on src/types/index.ts
> +export type ButtonSizeType = Extract<SizeType, 'sm' | 'md' | 'lg'>;
저 또 궁금한 부분이 있습니다!
Extract로 SizeType에 3가지 타입을 추출해오셨는데, 
일반적으로 'sm' | 'md' | 'lg'로 사용하지 않는 이유가 있을까요?
Extract를 어떤 때에 사용하는지 궁금합니다

2021-12-01 06:12 UTC, SeungrokYoon reviewed
사휘님~ 코드리뷰 완료했습니다~ 상혁님과 함께 사휘님의 코드를 뜯어보는 시간을 가졌는데 궁금한 점이 몇 가지 생겨서 코멘트 남겼습니다. 고생하셨어요!

2021-12-01 06:12 UTC, SeungrokYoon commented on src/stories/Button.stories.tsx
> +  children: ReactElement<TextProps>;
/base/Button/index.tsx 에서 버튼 컴포넌트에서의 ButtonProps인터페이스에서는 children 이 주석 처리가 되어 있던데, `children` 이라는 prop에 특별한 기능이 있는 것인지 궁금합니다.

2021-12-01 06:12 UTC, SeungrokYoon commented on src/utils/constants/color.ts
> +};
디자인 시스템이 확립되면 값은 수정되긴 해야겠지만, 이렇게 테마 색상을 상수화하는 방법은 굉장히 좋네요

2021-12-01 07:37 UTC, 42KIM commented on src/components/base/Button/index.tsx
> +`;
@sshyukk 
스타일드 컴포넌트 내부에서 해당 스타일드 컴포넌트에 전달한 props를 받아서 위의 코드처럼 변수로 사용하기 위해서는
템플릿 리터럴 내부에서 함수를 선언해야 할 거예요.
함수를 선언했을 때 그 함수의 파라미터에 ```props```가 자동으로 할당이 돼요.
그래서 props.size, props.color 이런 식으로 사용하는 방식입니다. 위에서는 props.size를 그냥 디스트럭처링 할당해서 { size }라고 한 것뿐입니다.

함수의 파라미터로 props를 받아서 사용하지 않고 말씀하신 것처럼 그냥 props.size로 사용하려고 하면
props 라는 식별자가 존재하지 않는 식별자이기 때문에 에러가 뜰 거예요

결론은 그냥 스타일드 컴포넌트에서 props를 받아서 사용하기 위해서는 함수로 사용해야 한다 일 것 같네요.

2021-12-01 07:39 UTC, 42KIM commented on src/stories/Button.stories.tsx
> +  children: ReactElement<TextProps>;
@sshyukk 
이 부분은 수정이 덜 됐네요 ㅠ
아마 ReactJSXElement로 표기된 부분은 전부 ReactElement로 바꿀 것 같아요.

그리고 TextProps를 준 것은
저 ReactElement에는 Text 컴포넌트의 props인 TextProps만 들어올 수 있도록 하기 위해서 해놨는데
저 부분도 더 나은 방법이 있는지 조금 더 알아보긴 해야 할 것 같습니다

2021-12-01 07:40 UTC, 42KIM commented on src/types/index.ts
> +export type ButtonSizeType = Extract<SizeType, 'sm' | 'md' | 'lg'>;
@sshyukk 
Extract 자체는 말그대로 기존에 존재하는 타입에서 일부를 추출해서 사용할 때 쓰는 거라고 찾았는데요
저도 굳이 저렇게 해야하나 싶기는한데, 
이미 Size라는 타입을 정의해둔 게 있어서 저렇게 하긴 했거든요
근데 이거는 디자인 시스템이 완성이 돼서 Button type을 뭐뭐로 줄 것인지 정해진다면 수정될 부분이라고 생각합니다

2021-12-01 07:41 UTC, 42KIM commented on src/stories/Button.stories.tsx
> +  type: 'button' | 'reset' | 'submit';
@SeungrokYoon 
버튼 type은 우리가 커스텀해서 정하는 게 아니라 원래 저 세 가지로 정해져있으니까
굳이 새로운 타입으로 만들필요가 없지 않나 해서 그냥 바로 적었습니다
그 외에 딱히 별 다른 이유는 없었어요
따로 빼야 할까요?

2021-12-01 07:45 UTC, 42KIM commented on src/stories/Button.stories.tsx
> +  children: ReactElement<TextProps>;
@SeungrokYoon 
children을 주석 처리한 이유는
무호님이 작업 중인 Text 컴포넌트가 완성되면 그 컴포넌트만 들어올 수 있도록 코드를 수정하려고 해서 그렇습니다
이거 말씀하시기 전에 까먹고 있었는데
그냥 ReactNode 타입으로 바꿔야할 것 같네여

2021-12-01 07:46 UTC, 42KIM commented on src/utils/constants/color.ts
> +};
@SeungrokYoon
아마 저희가 디자인 시스템에서 주로 사용되는 모든 색상에 대해서는 이렇게 상수화 시켜서 관리해야할듯 싶네요!

2021-12-03 08:17 UTC, sshyukk commented on src/components/base/Button/index.tsx
> +`;
스타일드 컴포넌트를 사용할 때에는 프롭스를 먼저 받아내고 그 안에서 함수로 사용해야되는 것이군요.

2021-12-03 08:22 UTC, sshyukk commented on src/stories/Button.stories.tsx
> +  children: ReactElement<TextProps>;
ReactElement가 ReactJSXElement를 포함하는 개념이군요.
TextProps는 컴포넌트를 받기 위해 만들어 놓은 것도 알았습니다.

2021-12-03 08:23 UTC, sshyukk commented on src/types/index.ts
> +export type ButtonSizeType = Extract<SizeType, 'sm' | 'md' | 'lg'>;
아 그렇군요 감사합니다!

2021-12-04 12:25 UTC, merged

2021-12-06 14:35 UTC, sshyukk reviewed
늦었지만 구현하시느라 고생하셨습니다! 새로운 방법 많이 알아가네요

2021-12-06 14:35 UTC, sshyukk commented on src/components/base/Button/types.ts
> +type ButtonSizeKeys = keyof typeof BUTTON_SIZE;
keyof typeof를 사용하여 코드를 간결하게 유지한 부분 좋습니다!

2021-12-06 14:35 UTC, sshyukk commented on src/stories/Button.stories.tsx
> +interface ButtonProps {
이 부분은 base 컴포넌트의 types에서 import하지 않고 따로 지정해준 이유가 있을까요?